const GRAD_COLOR_1 = '#0F1B32';
const GRAD_COLOR_2 = '#437BA2';
const HOVER_COLOR = '#A343E3';

const SIDE_COLOR = '#3C75BF';
const SIDE_HOVER_COLOR = '#B1119E';

const EXTRUDE_DEPTH = 4.0;

const LINE_WIDTH = 1.5;
const LINE_COLOR = '#97DCEF';
const SURFACE_LINE_Z = 4.01;

const EXTRUDE_GEO_PARAMS = { depth: EXTRUDE_DEPTH, bevelEnabled: false };
const LINE_MAT_PARAMS = { color: LINE_COLOR, linewidth: LINE_WIDTH };

export {
  GRAD_COLOR_1,
  GRAD_COLOR_2,
  HOVER_COLOR,
  SIDE_COLOR,
  SIDE_HOVER_COLOR,
  LINE_MAT_PARAMS,
  EXTRUDE_GEO_PARAMS,
  SURFACE_LINE_Z,
};
